# Generated by Django 2.2.6 on 2020-08-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_django_teams', '0002_rename_organisations_to_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='permissions',
            field=models.CharField(choices=[('R', 'Read'), ('X', 'Execute'), ('W', 'Write'), ('A', 'Admin')], default='R', max_length=1),
        ),
    ]
